name: Simple PR Builder Workflow

on:
  workflow_call:
    inputs:
      TEST_COMMAND:
        description: 'Extra commands to execute as part of test steps'
        type: string
        default: ''

    secrets:
      SHARED_ACTIONS_SSH_KEY:
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key Id for CodeArtifact package retriever'
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_SECRET:
        description: 'AWS Access Key Secret for CodeArtifact package retriever'
        required: true
      GITHUB_PACKAGE_ACCESS_TOKEN:
        description: 'Github package access token for @soltalabs package'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          repository: soltalabs/actions
          ref: v1.1
          path: ./.github/actions/solta

      - name: Configure CodeArtifact packages access
        uses: ./.github/actions/solta/packages-access
        with:
          aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_SECRET }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        uses: ./.github/actions/solta/install-from-cache
        with:
          codeartifact-auth-token: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          npm-token: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}

      - name: Run tests
        run: |
          yarn test --passWithNoTests
          ${{ inputs.TEST_COMMAND }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}
