name: Simple service deployment (ECR)

on:
  workflow_call:
    inputs:
      ECR_NAME:
        description: 'The repository name (ECR)'
        required: true
        type: string
      ECS_CLUSTER_NAME:
        description: 'The service cluster name (ECS)'
        required: true
        type: string
      ECS_SERVICE_NAME:
        description: 'The service name (ECS)'
        required: true
        type: string
      AWS_REGION:
        description: 'AWS Region the workflow to be deployed in'
        type: string
        default: 'ap-southeast-2'
      AWS_DEFAULT_OUTPUT:
        description: 'Default output for AWS call'
        type: string
        default: 'json'

    secrets:
      SHARED_ACTIONS_SSH_KEY:
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key Id for CodeArtifact package retriever'
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_SECRET:
        description: 'AWS Access Key Secret for CodeArtifact package retriever'
        required: true
      DEV_AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key Id for DEV environment'
        required: true
      DEV_AWS_ACCESS_KEY_SECRET:
        description: 'AWS Access Key Secret for DEV environment'
        required: true
      SANDBOX_AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key Id for SANDBOX environment'
        required: true
      SANDBOX_AWS_ACCESS_KEY_SECRET:
        description: 'AWS Access Key Secret for SANDBOX environment'
        required: true
      GITHUB_PACKAGE_ACCESS_TOKEN:
        required: true
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          ref: v1.1
          repository: soltalabs/actions
          path: ./.github/actions/solta
      - name: Configure CodeArtifact packages access
        uses: ./.github/actions/solta/packages-access
        with:
          aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_SECRET }}
      - name: Build & Store ECS Image
        uses: ./.github/actions/solta/build-ecs-image
        with:
          ecr-name: ${{ inputs.ECR_NAME}}
          ecs-service-name: ${{ inputs.ECS_SERVICE_NAME }}
          code-artifact-auth-token: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          npm-token: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          ref: v1.1
          repository: soltalabs/actions
          path: ./.github/actions/solta
      - name: Deploy to ECS
        uses: ./.github/actions/solta/deploy-ecs
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET}}
          ecr-name: ${{ inputs.ECR_NAME}}
          ecs-cluster-name: dev-${{ inputs.ECS_CLUSTER_NAME }}
          ecs-service-name: ${{ inputs.ECS_SERVICE_NAME }}
          wait-for-service-stability: false

  deploy-sandbox:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          ref: v1.1
          repository: soltalabs/actions
          path: ./.github/actions/solta
      - name: Deploy to ECS
        uses: ./.github/actions/solta/deploy-ecs
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_SECRET}}
          ecr-name: ${{ inputs.ECR_NAME}}
          ecs-cluster-name: sandbox-${{ inputs.ECS_CLUSTER_NAME }}
          ecs-service-name: ${{ inputs.ECS_SERVICE_NAME }}
          wait-for-service-stability: false
