name: Simple Serverless workflow

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        description: "Node.js version"
        type: string
        default: "16"
      AWS_REGION:
        description: "AWS Region the workflow to be deployed in"
        type: string
        default: "ap-southeast-2"
      AWS_DEFAULT_OUTPUT:
        description: "Default output for AWS call"
        type: string
        default: "json"

    secrets:
      SHARED_ACTIONS_SSH_KEY:
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_ID:
        description: "AWS Access Key Id for CodeArtifact package retriever"
        required: true
      CODEARTIFACT_AWS_ACCESS_KEY_SECRET:
        description: "AWS Access Key Secret for CodeArtifact package retriever"
        required: true
      DEV_AWS_ACCESS_KEY_ID:
        description: "AWS Access Key Id for DEV environment"
        required: true
      DEV_AWS_ACCESS_KEY_SECRET:
        description: "AWS Access Key Secret for DEV environment"
        required: true
      GITHUB_PACKAGE_ACCESS_TOKEN:
        description: "Github access token"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          ref: v1.2
          repository: soltalabs/actions
          path: ./.github/actions/solta
      - name: Configure CodeArtifact packages access
        uses: ./.github/actions/solta/packages-access
        with:
          aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_SECRET }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      - name: Install dependencies
        uses: ./.github/actions/solta/install-from-cache
        with:
          codeartifact-auth-token: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          npm-token: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}
      - name: Build
        run: |
          yarn build
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Deploy to AWS DEV
        uses: serverless/github-action@v3.2.0
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
